stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - apk add --no-cache git
    - git config --global user.email "ci@gitlab"
    - git config --global user.name "GitLab CI"
  script:
    - git fetch origin main
    - git checkout -B main origin/main
    - git remote remove github || true
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/Zocker7sea/pumping-lemma-visualization.git
    - git push github main