stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine/git
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - git config --global user.email "ci@gitlab"
    - git config --global user.name "GitLab CI"
    - git remote remove github || true
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/Zocker7sea/pumping-lemma-visualization.git
    - git push --mirror github
