apiVersion: v1
kind: Service
metadata:
  name: pumping-lemma-service
spec:
  selector:
    app: pumping-lemma-visualization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
  type: ClusterIP
